#!/usr/bin/env tsx
/** Extract contract ABIs and append the hand-curated ERC20 subset. */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..", "..");

interface Artifact {
  abi: unknown[];
}

const ARTIFACTS = [
  { name: "SENTRY_ORACLE_ABI", path: "contracts/out/SentryOracle.sol/SentryOracle.json" },
  { name: "SENTRY_QUEUE_ABI", path: "contracts/out/SentryQueue.sol/SentryQueue.json" },
  { name: "SENTRY_AGENT_REGISTRY_ABI", path: "contracts/out/SentryAgentRegistry.sol/SentryAgentRegistry.json" },
];

const banner = `// SPDX-License-Identifier: MIT
// AUTO-GENERATED by sdk/scripts/extract-abis.ts. Do not edit by hand.
// Run \`pnpm run extract-abis\` from sdk/ to regenerate after contracts change.

`;

const ERC20_HANDWRITTEN = [
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "totalSupply", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "account", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "transfer", stateMutability: "nonpayable", inputs: [{ name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "transferFrom", stateMutability: "nonpayable", inputs: [{ name: "from", type: "address" }, { name: "to", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "event", name: "Transfer", inputs: [{ indexed: true, name: "from", type: "address" }, { indexed: true, name: "to", type: "address" }, { indexed: false, name: "value", type: "uint256" }] },
  { type: "event", name: "Approval", inputs: [{ indexed: true, name: "owner", type: "address" }, { indexed: true, name: "spender", type: "address" }, { indexed: false, name: "value", type: "uint256" }] },
];

let out = banner;
for (const { name, path } of ARTIFACTS) {
  const full = resolve(root, path);
  const raw = readFileSync(full, "utf-8");
  const artifact = JSON.parse(raw) as Artifact;
  out += `export const ${name} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n`;
}

out += `export const ERC20_ABI = ${JSON.stringify(ERC20_HANDWRITTEN, null, 2)} as const;\n`;

const target = resolve(__dirname, "..", "src", "abi.ts");
writeFileSync(target, out);
console.log(`wrote ${target} (${ARTIFACTS.length} forge ABI + ERC20_ABI standard)`);
